---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.utils": '>=2.0.0'
license_file: LICENSE
name: netcommon
namespace: ansible
description: Ansible Collection with common content to help automate the management of network, security, and cloud devices.
readme: README.md
repository: https://github.com/ansible-collections/ansible.netcommon
issues: https://github.com/ansible-collections/ansible.netcommon/issues
tags: [networking, security, cloud, network_cli, netconf, httpapi, grpc]
# NOTE(pabelanger): We create an empty version key to keep ansible-galaxy
# happy. We dynamically inject version info based on git information.
version: null
