---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.utils": ">=3.0.0"
license_file: LICENSE
name: netcommon
namespace: ansible
description:
  Ansible Collection with common content to help automate the management
  of network, security, and cloud devices.
readme: README.md
repository: https://github.com/ansible-collections/ansible.netcommon
issues: https://github.com/ansible-collections/ansible.netcommon/issues
tags: [networking, security, cloud, network_cli, netconf, httpapi, grpc]
build_ignore:
  - .yamllint
  - .prettierignore
  - .pre-commit-config.yaml
  - .isort.cfg
  - .gitignore
  - .flake8
  - .ansible-lint
  - sonar-project.properties
  - codecov.yml
  - .github/
version: 8.2.1
