---yort=$((iosxr_last_octet + 3000))
          iosxr_grpc_port=57400

          iosxe_last_octet="${iosxe_ip##*.}"
          iosxe_ssh_port=$((iosxe_last_octet + 2000))
          iosxe_https_port=$((iosxe_last_octet + 4000))
          iosxe_http_port=$((iosxe_last_octet + 8000))
          iosxe_netconf_port=$((iosxe_last_octet + 3000))

          ubuntu_last_octet="${ubuntu_ip##*.}"
          ubuntu_ssh_port=$((ubuntu_last_octet + 2000))

          # Destination host for port-forwarded access
          dest_host="54.190.208.146"
          out_file="$RUNNER_TEMP/inventory-${{ matrix.ansible_version }}.ini"
          ansible localhost -c local -m template -a "src=tests/integration/labs/inventory.j2 dest=$out_file mode=0644" \
            -e "ansible_host=$dest_host ansible_network_cli_ssh_type=$CLI_SSH_TYPE \
            nxos_ssh_port=$nxos_ssh_port nxos_http_port=$nxos_http_port nxos_netconf_port=$nxos_netconf_port \
            iosxr_netconf_port=$iosxr_netconf_port iosxr_grpc_port=$iosxr_grpc_port ubuntu_ssh_port=$ubuntu_ssh_port \
            iosxe_http_port=$iosxe_http_port iosxr_ssh_port=$iosxr_ssh_port iosxe_ssh_port=$iosxe_ssh_port"
          echo "inventory_path=$out_file" >> "$GITHUB_OUTPUT"

      - name: DEBUG Print the ansible version
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug == 'true' || github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'debug') }}
        run: ansible --version

      - name: DEBUG inventory
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug == 'true' || github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'debug') }}
        shell: bash
        run: |
          echo "Inventory path: ${{ steps.render_inventory.outputs.inventory_path }}"
          echo
          cat "${{ steps.render_inventory.outputs.inventory_path }}"

      - name: DEBUG libssh and pylibssh versions
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug == 'true' || github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'debug') }}
        shell: bash
        run: python -c "from pylibsshext import __full_version__; print(__full_version__)"

      - name: Run ansible-test network-integration - all
        run: ansible-test network-integration --inventory "${{ steps.render_inventory.outputs.inventory_path }}" -vvvv
        working-directory: ${{ steps.identify.outputs.collection_path }}
        env:
          LAB_NODES: ${{ needs.lab-create.outputs.lab_nodes_json }}

  lab-destroy:
    if: ${{ always() }}
    needs: integration-tests
    uses: ansible/ansible-content-actions/.github/workflows/cml_lab_destroy.yaml@main
    secrets:
      virl_host: ${{ secrets.VIRL_HOST }}
      virl_username: ${{ secrets.VIRL_USERNAME }}
      virl_password: ${{ secrets.VIRL_PASSWORD }}
