---
name: Integration
on:
  pull_request_target:
    branches: [main]
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - "plugins/**"
      - "tests/integration/**"
  workflow_dispatch:
jobs:
  safe-to-test:
    if: >-
      github.event.label.name == 'safe to test' ||
      github.event.action != 'labeled'
    uses: ansible-network/github_actions/.github/workflows/safe-to-test.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  integration:
    uses: ansible/ansible-content-actions/.github/workflows/network_integration.yaml@main
    needs:
      - safe-to-test
    with:
      lab_title: ansible_netcommon
      network_os: ansible.netcommon.netcommon
      pytest_addopts: "--color=yes -n 2 --log-level WARNING -vvv"
      collection_pre_install: >-
        git+https://github.com/ansible-collections/ansible.utils.git
    secrets:
      cml_ssh_password: ${{ secrets.CML_SSH_PASSWORD }}
      virl_host: ${{ secrets.VIRL_HOST }}
      virl_password: ${{ secrets.VIRL_PASSWORD }}
