---
name: refresh_automation_hub_token
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  refresh:
    uses: ansible/devtools/.github/workflows/ah_token_refresh.yml@main
    with:
      environment: release
    secrets:
      ah_token: ${{ secrets.AH_TOKEN }}
