---
name: refresh_automation_hub_token
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  refresh:
    uses: ansible/ansible-content-actions/.github/workflows/refresh_ah_token.yaml@main
    with:
      environment: release
    secrets:
      ah_token: ${{ secrets.AH_TOKEN }}
